### PR TITLE
QOL fixes

### LINKED ISSUE #186: The X button in the Edit Javadoc window doesn't work
You have to click "Cancel" or "Save" for it to close. I think a popup saying "Do you want to lose unsaved changes?" or something similar should appear if you click the X with unsaved changes in the javadoc box.

### PR DESCRIPTION
**Pull request by Yanis48**
Not as epic as Earthcomputer's PR, but enjoy this small contribution.

- Closing the Open Jar dialog without selecting anything no longer crashes Enigma
- Generate Stats dialog now appears centered instead of the top left of the screen
- Change Language dialog size is now related to the text length (the text in french is now readable)
- Popup Menu now displays the actual shortcuts (Ctrl + letter instead of just the letter)
- The shortcut to show the specific calls menu now works
- The X button now works in Crash and Javadoc dialogs (closes #186)
- ~~Obfuscated classes no longer stay in the obfuscated panel once they are renamed~~
- Removed useless imports on various classes

### CODE REVIEW

File: src/main/java/cuchaz/enigma/gui/elements/PopupMenuBar.java [hunk 1]
```diff
@@ -24,79 +24,79 @@ public PopupMenuBar(Gui gui) {
 		{
 			JMenuItem menu = new JMenuItem(I18n.translate("popup_menu.rename"));
 			menu.addActionListener(event -> gui.startRename());
-			menu.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_R, 0));
+			menu.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_R, InputEvent.CTRL_MASK));
```
Comment (Earthcomputer) [inline src/main/java/cuchaz/enigma/gui/elements/PopupMenuBar.java:27]:
```suggestion
			menu.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_R, InputEvent.CTRL_DOWN_MASK));
```
Along with similar changes below

Comment (Yanis48) [reply src/main/java/cuchaz/enigma/gui/elements/PopupMenuBar.java]: Done

**Comment by Yanis48** [comment]
Reverted the obf to deobf change as it doesn't seem to work as I expected after further testing
